name: Create GitHub Release
on: 
  workflow_dispatch:
     inputs:
       version:
         required: true
         description: "Version Number"
         default: 2.0.14

jobs:  
  build-test-publish:   
    permissions: write-all
    name: Creating Github Release
    uses: gunpal5/workflows/.github/workflows/dotnet_build-test-publish.yml@main       
    with:
      generate-build-number: false
      create-release: true
      publish: true
      project-version: ${{ inputs.version }}
