name: Publish Nuget Packages
on: 
  workflow_dispatch:
     inputs:
       version:
         required: true
         description: "Version Number"
         default: v2.0.14

jobs:  
  build-test-publish:   
    name: Creating Github Release
    uses: gunpal5/workflows/.github/workflows/dotnet_build-test-publish.yml@main       
    with:
      generate-build-number: true
      create-release: true
      project-version: ${{ needs.update.outputs.new_version }}
