name: Build and Publish To Nuget
on: [ workflow_dispatch ]

jobs:  
  build-test-publish:   
    name: Build, test and publish
    uses: gunpal5/workflows/.github/workflows/dotnet_build-test-publish.yml@main
    secrets:
      nuget-key: ${{ secrets.NUGET_KEY }}
    with:
      generate-build-number: true
      create-release: true
      
